CREATE TABLE sys_org
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    org_name   VARCHAR(64) NOT NULL,
--     org_code      VARCHAR(32),
    parent_id  BIGINT,
    order_no   varchar(40) not null,
--     level         smallint    not null,
    full_seq   varchar(255),
--     full_name  varchar(255),
    master_id  bigint,
--     is_enabled BOOLEAN     NOT NULL DEFAULT TRUE,

    is_deleted BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) references sys_org (id)
);

COMMENT
ON TABLE sys_org IS '组织机构表';

COMMENT
ON COLUMN sys_org.id IS '机构ID';
COMMENT
ON COLUMN sys_org.org_name IS '机构名称';
-- COMMENT ON COLUMN sys_org.org_code IS 'code（业务用，ID系统用）';
COMMENT
ON COLUMN sys_org.parent_id IS '上级部门ID，顶级部门可为NULL';
COMMENT
ON COLUMN sys_org.order_no IS '机构排序码';
-- COMMENT ON COLUMN sys_org.level IS '层级';
COMMENT
ON COLUMN sys_org.full_seq IS '部门完整路径，如 1/3/5';
-- COMMENT ON COLUMN sys_org.full_name IS '部门完整路径名称，用 / 分隔，如 总部/研发部/算法组';
COMMENT
ON COLUMN sys_org.master_id IS '主数据ID';
COMMENT
ON COLUMN sys_org.created_at IS '创建时间';
COMMENT
ON COLUMN sys_org.updated_at IS '更新时间';

-- 按单位+状态查询部门
-- CREATE INDEX idx_sys_org_uint
--     ON sys_org (unit_id)
--     WHERE is_deleted = FALSE;
--
-- COMMENT ON INDEX idx_sys_org_uint IS '按单位查询部门';


-- 按部门code查询
-- CREATE INDEX idx_sys_org_code
--     ON sys_org (org_code)
--     WHERE is_deleted = FALSE;

-- COMMENT ON INDEX idx_sys_org_code IS '按部门code查询';

-- 按父部门查子部门
CREATE INDEX idx_sys_org_parent
    ON sys_org (parent_id) WHERE is_deleted = FALSE;

COMMENT
ON INDEX idx_sys_org_parent IS '按父部门ID查询子部门';

-- 按 full_seq 查询（比如子树查询）
CREATE INDEX idx_sys_org_full_seq
    ON sys_org (full_seq) WHERE is_deleted = FALSE;

COMMENT
ON INDEX idx_sys_org_full_seq IS '按 full_seq 查询部门树';

SELECT setval(
               'data_standard.sys_org_id_seq',
               COALESCE((SELECT MAX(id) FROM data_standard.sys_org), 0) + 1,
               false
       );
