CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE sys_user
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(64) NOT NULL,
    org_id     BIGINT      NOT NULL,
    mobile     VARCHAR(20),
    id_card    VARCHAR(32),
    password   VARCHAR(64),
    is_enabled BOOLEAN     NOT NULL DEFAULT TRUE,
    master_id  bigint,
    is_deleted BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (org_id) references sys_org (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);


COMMENT ON TABLE sys_user IS '系统用户表';

COMMENT ON COLUMN sys_user.id IS '用户ID';
COMMENT ON COLUMN sys_user.username IS '姓名';
COMMENT ON COLUMN sys_user.org_id IS '所属部门ID';
COMMENT ON COLUMN sys_user.mobile IS '手机号（可为空）';
COMMENT ON COLUMN sys_user.id_card IS '证件号（如身份证、护照等）';
COMMENT ON COLUMN sys_user.password IS '密码';
COMMENT ON COLUMN sys_user.master_id IS '主数据ID';
COMMENT ON COLUMN sys_user.is_deleted IS '是否删除（软删除标识）';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';

-- CREATE UNIQUE INDEX uk_sys_user_mobile
--     ON sys_user (mobile)
--     WHERE is_deleted = FALSE AND mobile IS NOT NULL;
--
-- COMMENT ON INDEX uk_sys_user_mobile IS '手机号唯一索引（未删除且手机号非空用户）';
--
-- CREATE UNIQUE INDEX uk_sys_user_id_card
--     ON sys_user (id_card)
--     WHERE is_deleted = FALSE AND id_card IS NOT NULL;
--
-- COMMENT ON INDEX uk_sys_user_id_card IS '证件号唯一索引（未删除且证件号非空用户）';


CREATE INDEX idx_sys_user_org
    ON sys_user (org_id)
    WHERE is_deleted = FALSE;
COMMENT ON INDEX idx_sys_user_org IS '按机构查询用户';
--
-- CREATE INDEX idx_sys_user_dept
--     ON sys_user (dept_id)
--     WHERE is_deleted = FALSE;
--
-- COMMENT ON INDEX idx_sys_user_org IS '按单位查询用户';

CREATE INDEX idx_sys_user_username_trgm
    ON sys_user USING gin (username gin_trgm_ops)
    WHERE is_deleted = FALSE;
COMMENT ON INDEX idx_sys_user_username_trgm IS '按姓名查用户';

-- CREATE INDEX idx_sys_user_status_enabled
--     ON sys_user (status, is_enabled)
--     WHERE is_deleted = FALSE;
--
-- COMMENT ON INDEX idx_sys_user_status_enabled IS '按状态和启用标识查询用户';


SELECT setval(
               'data_standard.sys_user_id_seq',
               COALESCE((SELECT MAX(id) FROM data_standard.sys_user), 0) + 1,
               false
       );