create table sys_role
(
    id         bigint primary key generated by default as identity,
    code       varchar(64) not null unique, -- ADMIN / USER
    role_name  varchar(64) not null,
    is_enabled boolean              default true,

    is_deleted boolean              default false,
    created_at timestamptz not null default CURRENT_TIMESTAMP,
    updated_at timestamptz not null default current_timestamp
);

drop table sys_role;
