create table sys_permission
(
    id         bigint primary key generated by default as identity,
    parent_id  bigint,

    code       varchar(128) not null unique,
    perm_name  varchar(64)  not null,
    perm_type  varchar(16)  not null, -- MODULE / MENU / PAGE / ACTION

    path       varchar(255),
    component  varchar(255),
    icon       varchar(64),

    permission varchar(128),          -- user:add
    order_no   int                   default 0,
    is_visible boolean               default true,
    is_enabled boolean               default true,

    is_deleted boolean               default false,
    created_at timestamptz  not null default current_timestamp,
    updated_at timestamptz  not null default current_timestamp,

    constraint fk_permission_parent
        foreign key (parent_id) references sys_permission (id)
);

-- | 动作      | 含义      |
-- | ------- | ------- |
-- | view    | 查看 / 查询 |
-- | add     | 新增      |
-- | edit    | 修改      |
-- | delete  | 删除      |
-- | export  | 导出      |
-- | import  | 导入      |
-- | enable  | 启用      |
-- | disable | 禁用      |
-- | assign  | 分配      |
-- | reset   | 重置      |