CREATE TABLE biz_process_node_def
(
    id             bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     process_def_id  bigint NOT NULL REFERENCES biz_process_def(id), -- 关联流程定义
    process_def_id bigint       NOT NULL,                           -- 关联流程定义
    node_code      varchar(64)  NOT NULL,                           -- 节点编码
    node_name      varchar(128) NOT NULL,                           -- 节点名称
    node_type      varchar(32)  NOT NULL,                           -- 节点类型：START / APPROVAL / PARALLEL / END
    approve_type   varchar(32)           DEFAULT NULL,              -- 审批类型：SINGLE / ALL / ANY（会签）
    approve_param  jsonb                 DEFAULT NULL,              -- 比如会签的比例
    assignee_rule  varchar(64)           DEFAULT NULL,              -- 分配规则：ROLE / USER / SCRIPT
    assignee_value varchar(256)          DEFAULT NULL,              -- 分配值：角色ID / 用户ID / 表达式
    order_no       int          NOT NULL,                           -- 节点顺序号
    created_at     timestamptz  NOT NULL DEFAULT current_timestamp, -- 创建时间

    -- 唯一约束：同一流程中节点编码不能重复
    CONSTRAINT uk_process_node_code UNIQUE (process_def_id, node_code)
);


INSERT INTO biz_process_node_def (process_def_id, node_code, node_name, node_type, approve_type, assignee_value,assignee_rule,

                                  order_no)
VALUES (1, 'START', '提交计划', 'START', 'SINGLE', '100258217', 'USER', 1),
       (1, 'DEPT_APPROVAL', '业务部门审批', 'APPROVAL', 'SINGLE', '100259102', 'USER', 2),
       (1, 'KXB_APPROVAL', '科信部审批', 'APPROVAL', 'SINGLE', '12818912', 'USER', 3),
       (1, 'INFO_CENTER_APPROVAL', '信息中心审批', 'APPROVAL', 'SINGLE', '12312423', 'USER', 4),
       (1, 'END', '结束', 'END', null, null, null, 5);

COMMENT ON TABLE biz_process_node_def IS '流程节点定义';
-- 添加列注释
COMMENT ON COLUMN biz_process_node_def.id IS '主键ID';
COMMENT ON COLUMN biz_process_node_def.process_def_id IS '关联流程定义ID';
COMMENT ON COLUMN biz_process_node_def.node_code IS '节点编码';
COMMENT ON COLUMN biz_process_node_def.node_name IS '节点名称';
COMMENT ON COLUMN biz_process_node_def.node_type IS '节点类型：START / APPROVAL / PARALLEL / END';
COMMENT ON COLUMN biz_process_node_def.approve_type IS '审批类型：SINGLE / ALL / ANY（会签）';
COMMENT ON COLUMN biz_process_node_def.assignee_rule IS '分配规则：ROLE / USER / SCRIPT';
COMMENT ON COLUMN biz_process_node_def.assignee_value IS '分配值：角色ID / 用户ID / 表达式';
COMMENT ON COLUMN biz_process_node_def.order_no IS '节点顺序号';
COMMENT ON COLUMN biz_process_node_def.created_at IS '创建时间';

-- 添加表注释
COMMENT ON TABLE biz_process_node_def IS '流程节点定义表';

-- -- 可选：创建索引以提高查询性能
-- CREATE INDEX idx_process_node_def_process_def_id ON process_node_definition(process_def_id);
-- CREATE INDEX idx_process_node_def_order_no ON process_node_definition(order_no);