-- 4. 核心表：标准编制管理（精简版）
CREATE TABLE biz_std_plan
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    std_name        VARCHAR(200) NOT NULL UNIQUE,
    std_no          VARCHAR(50)  NOT NULL UNIQUE,
    std_type_id     INT          NOT NULL REFERENCES dict_std_type (id),
    std_nature      VARCHAR(10)  NOT NULL,
    orig_std_no     VARCHAR(50),

--     propose_org_id  BIGINT       NOT NULL REFERENCES sys_org (id),
    propose_org_id  BIGINT       NOT NULL,
--     tech_org_id     BIGINT       NOT NULL REFERENCES sys_org (id),
    tech_org_id     BIGINT       NOT NULL,
--     draft_org_id    BIGINT       NOT NULL REFERENCES sys_org (id),
    draft_org_id    BIGINT       NOT NULL,
--     charge_user_id  BIGINT       NOT NULL REFERENCES sys_user (id),
    charge_user_id  BIGINT       NOT NULL,

    comp_cycle      INT          NOT NULL,
    is_confidential BOOLEAN      NOT NULL,
    is_tibet        BOOLEAN      NOT NULL,

    basis           TEXT,
    content         TEXT,
    reason          TEXT,

    app_fee         NUMERIC(12, 2),
    decl_org_id     BIGINT,
    decl_time       timestamptz  NOT NULL,

    status          VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    tech_opinion    TEXT,
    grp_opinion     TEXT,

--     created_by      BIGINT       NOT NULL REFERENCES sys_user (id),
    created_by      BIGINT       NOT NULL,
    is_deleted      BOOLEAN      NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 表注释
COMMENT ON TABLE biz_std_plan IS '标准编制计划';

-- 列注释
COMMENT ON COLUMN biz_std_plan.id IS 'ID';
COMMENT ON COLUMN biz_std_plan.std_name IS '标准名称';
COMMENT ON COLUMN biz_std_plan.std_no IS '标准编号';
COMMENT ON COLUMN biz_std_plan.std_type_id IS '标准类型';
COMMENT ON COLUMN biz_std_plan.std_nature IS '标准性质,NEW（新增）,REVISION（修订）';
COMMENT ON COLUMN biz_std_plan.orig_std_no IS '原标准编号';

COMMENT ON COLUMN biz_std_plan.propose_org_id IS '制定部门ID';
COMMENT ON COLUMN biz_std_plan.tech_org_id IS '技术归口部门ID';
COMMENT ON COLUMN biz_std_plan.draft_org_id IS '主要起草单位';
COMMENT ON COLUMN biz_std_plan.charge_user_id IS '负责人';

COMMENT ON COLUMN biz_std_plan.comp_cycle IS '编制周期(月)';
COMMENT ON COLUMN biz_std_plan.is_confidential IS '是否涉密';
COMMENT ON COLUMN biz_std_plan.is_tibet IS '是否涉及川藏铁路';

COMMENT ON COLUMN biz_std_plan.basis IS '立项依据';
COMMENT ON COLUMN biz_std_plan.content IS '主要内容';
COMMENT ON COLUMN biz_std_plan.reason IS '立项理由';

COMMENT ON COLUMN biz_std_plan.app_fee IS '申请费用(万元)';
COMMENT ON COLUMN biz_std_plan.decl_org_id IS '申报单位';
COMMENT ON COLUMN biz_std_plan.decl_time IS '申报时间';

COMMENT ON COLUMN biz_std_plan.status IS 'DRAFT        草稿
SUBMITTED    已提交（进入流程）
APPROVING    审批中
APPROVED     已批准
REJECTED     已驳回
CANCELLED    已撤回（可选）';
COMMENT ON COLUMN biz_std_plan.tech_opinion IS '技术归口意见';
COMMENT ON COLUMN biz_std_plan.grp_opinion IS '科信部意见';
COMMENT ON COLUMN biz_std_plan.created_by IS '经办人';

COMMENT ON COLUMN biz_std_plan.is_deleted IS '逻辑删除';
COMMENT ON COLUMN biz_std_plan.created_at IS '创建时间';
COMMENT ON COLUMN biz_std_plan.updated_at IS '更新时间';


-- 1. 负责人，经办人必须是系统用户？