-- 标准发文的模板字段
create table biz_std_issue_field
(
    id            bigint primary key generated by default as identity,
    parent_id     bigint, -- 冗余字段
    filed_name    varchar(64) not null,
    field_type    VARCHAR(32) NOT NULL,
    required      BOOLEAN              DEFAULT FALSE,
    default_value VARCHAR(255)         default NULL,
    order_no      INT,
    config        jsonb,
    created_at    timestamptz NOT NULL default CURRENT_TIMESTAMP,
    updated_at    timestamptz not null default current_timestamp
);