create table biz_std_item_value
(
    id         bigint primary key generated by default as identity,
    item_id    bigint,
    field_id   bigint,
    value_str  VARCHAR(1024),
    value_num  DECIMAL(18, 2),
    value_date DATE,
    value_json JSONB,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);