-- 标准内容
create table biz_std_content
(
    id               bigint primary key generated by default as identity,
    -- 生成的附件ID
    gen_attach_id    bigint,
    -- 上传的附件ID
    upload_attach_id bigint,
    created_at       timestamptz not null default current_timestamp,
    updated_at       timestamptz not null default current_timestamp
);