CREATE TABLE biz_process_def
(
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    process_code varchar(64) UNIQUE,                             -- 流程编码，如 EXPENSE_APPROVAL
    process_name varchar(64),                                    -- 流程名称
    process_type varchar(32)          DEFAULT NULL,              -- 流程类型：标准计划审批，标准发布审批
    version      int         NOT NULL DEFAULT 1,                 -- 版本号（关键字段）
    is_enabled   BOOLEAN     NOT NULL DEFAULT True,              -- 状态：ENABLED / DISABLED
    description  text,                                           -- 流程描述
    created_by   BIGINT,                                         -- 创建人
    created_at   timestamptz NOT NULL DEFAULT current_timestamp, -- 创建时间
    updated_at   timestamptz NOT NULL DEFAULT current_timestamp  -- 更新时间
);


INSERT INTO biz_process_def(process_code, process_name, version, is_enabled, description)
VALUES ('STD_PLAN_RELEASE', '标准计划发布', 1, True, '标准计划拟稿-审核-发布流程');

-- 添加列注释
COMMENT ON COLUMN biz_process_def.id IS '主键ID';
COMMENT ON COLUMN biz_process_def.process_code IS '流程编码，如 EXPENSE_APPROVAL';
COMMENT ON COLUMN biz_process_def.process_name IS '流程名称';
COMMENT ON COLUMN biz_process_def.process_type IS '流程类型：标准计划审批/标准发布审批';
COMMENT ON COLUMN biz_process_def.version IS '版本号（关键字段）';
COMMENT ON COLUMN biz_process_def.is_enabled IS '状态：ENABLED / DISABLED';
COMMENT ON COLUMN biz_process_def.description IS '流程描述';
COMMENT ON COLUMN biz_process_def.created_by IS '创建人';
COMMENT ON COLUMN biz_process_def.created_at IS '创建时间';
COMMENT ON COLUMN biz_process_def.updated_at IS '更新时间';

-- 添加表注释
COMMENT ON TABLE biz_process_def IS '流程定义表';