-- 审批意见，某人在某个流程的某个节点的某个任务的审批意见

CREATE TABLE biz_process_opinion
(
    id              bigint primary key GENERATED BY DEFAULT AS IDENTITY,
    process_inst_id bigint      NOT NULL,
    node_inst_id    bigint      NOT NULL,
    task_id         bigint      NOT NULL,
    user_id         bigint      NOT NULL,
    username        varchar(64) NOT NULL,
    opinion_text    varchar(512)         default '',
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp
);

-- 为表添加注释
COMMENT ON TABLE biz_process_opinion IS '审批意见表：记录某人在某个流程实例的某个节点任务中提交的审批意见';

-- 为各字段添加注释
COMMENT ON COLUMN biz_process_opinion.id IS '主键，自增ID';
COMMENT ON COLUMN biz_process_opinion.process_inst_id IS '流程实例ID，标识所属的流程执行实例';
COMMENT ON COLUMN biz_process_opinion.node_inst_id IS '节点实例ID，标识该意见所属的流程节点实例';
COMMENT ON COLUMN biz_process_opinion.task_id IS '任务ID，关联 process_task 表的 id 字段，表示具体审批任务';
COMMENT ON COLUMN biz_process_opinion.user_id IS '审批人用户ID';
COMMENT ON COLUMN biz_process_opinion.username IS '审批人用户名';
COMMENT ON COLUMN biz_process_opinion.opinion_text IS '审批意见内容，最大长度512字符，默认为空字符串';
COMMENT ON COLUMN biz_process_opinion.created_at IS '记录创建时间，带时区的时间戳';
COMMENT ON COLUMN biz_process_opinion.updated_at IS '记录最后更新时间，带时区的时间戳';