-- 标准项的表头
create table biz_std_item_field
(
    id            bigint primary key generated by default as identity,
    --
    cat_id        bigint      not null,
    prop_id       bigint      NOT NULL,
    filed_name    varchar(64) not null,
    field_type    VARCHAR(32) NOT NULL,            --
    required      BOOLEAN              DEFAULT FALSE,
    default_value VARCHAR(255)         default NULL,
    order_no      INT,
    config        jsonb,
    created_at    timestamptz NOT NULL default CURRENT_TIMESTAMP,
    updated_at    timestamptz not null default current_timestamp
);

COMMENT ON COLUMN biz_std_item_field.field_type is 'text | textarea | number | date | datetime
select | multiselect | checkbox | radio
user | dept | attachment'