-- 数据标准项
create table biz_std_item
(
    id         bigint primary key generated by default as identity,
    std_id     bigint      not null references biz_std (id),
    -- 数据元编号
    code       varchar(32),
    order_no   int,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);