create table biz_std_issue_value
(
    id         bigint primary key generated by default as identity,
    issue_id   bigint,
    field_id   bigint,
    value_str  text,
    -- word元素类型
    value_type varchar(32),
    value_json JSONB,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);