CREATE TABLE biz_process_instance
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY,

    process_def_id    bigint      NOT NULL,
    process_code      varchar(64),
    process_version   int,

    biz_id            varchar(64),
    biz_type          varchar(32),
    biz_code          varchar(64),
    biz_title         varchar(256),

    status            varchar(32),

    current_node_code varchar(64),
    current_node_name varchar(128),

    start_user_id     bigint,
    start_user_name   varchar(64),
    start_dept_id     bigint,
    start_dept_name   varchar(128),

    start_source      varchar(32),

    end_reason        varchar(64),
    end_remark        varchar(256),

    created_by        bigint      NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at        timestamptz NOT NULL DEFAULT current_timestamp,
    end_time          timestamptz          DEFAULT NULL
);

COMMENT ON table biz_process_instance is '流程实例表';

COMMENT ON COLUMN biz_process_instance.id IS '主键ID';
COMMENT ON COLUMN biz_process_instance.process_def_id IS '流程定义ID';
COMMENT ON COLUMN biz_process_instance.process_code IS '流程编码，冗余字段，历史快照';
COMMENT ON COLUMN biz_process_instance.process_version IS '流程版本，冗余字段，历史快照';
COMMENT ON COLUMN biz_process_instance.biz_id IS '业务ID';
COMMENT ON COLUMN biz_process_instance.biz_type IS '业务类型';
COMMENT ON COLUMN biz_process_instance.biz_code IS '业务编码，如STD_PLAN-2026-001';
COMMENT ON COLUMN biz_process_instance.biz_title IS '业务标题，如车辆部2026动车组轮对数据标准计划发布';
COMMENT ON COLUMN biz_process_instance.status IS '状态，DRAFT        草稿
RUNNING      流转中
COMPLETED    正常结束
REJECTED     被驳回结束
WITHDRAWN    发起人撤回
CANCELED     管理员作废
SUSPENDED    挂起（可选）';
COMMENT ON COLUMN biz_process_instance.status IS '状态，DRAFT        草稿
RUNNING      流转中
COMPLETED    正常结束
REJECTED     被驳回结束
WITHDRAWN    发起人撤回
CANCELED     管理员作废
SUSPENDED    挂起（可选）
';
COMMENT ON COLUMN biz_process_instance.current_node_code IS '当前节点编码';
COMMENT ON COLUMN biz_process_instance.current_node_name IS '当前节点名称';
COMMENT ON COLUMN biz_process_instance.start_user_id IS '发起用户ID';
COMMENT ON COLUMN biz_process_instance.start_user_name IS '发起用户姓名';
COMMENT ON COLUMN biz_process_instance.start_dept_id IS '发起部门ID';
COMMENT ON COLUMN biz_process_instance.start_dept_name IS '发起部门名称';
COMMENT ON COLUMN biz_process_instance.start_source IS '发起来源';
COMMENT ON COLUMN biz_process_instance.end_reason IS '结束原因';
COMMENT ON COLUMN biz_process_instance.end_remark IS '结束备注';
COMMENT ON COLUMN biz_process_instance.created_by IS '创建人ID';
COMMENT ON COLUMN biz_process_instance.created_at IS '创建时间';
COMMENT ON COLUMN biz_process_instance.updated_at IS '更新时间';
COMMENT ON COLUMN biz_process_instance.end_time IS '结束时间';