create table biz_std
(
    id       bigint primary key generated by default as identity,
    std_no   varchar(128) unique,
    std_name varchar(256) not null unique,
    version  int          not null,
    refs     text,
    scope
    org_id   bigint       not null,

)