create table biz_process_action
(
    id              bigint primary key generated by default as identity,
    process_inst_id bigint      not null,
    node_inst_id    bigint      not null,
    task_id         bigint      not null,
    action_type     varchar(32), -- APPROVE / REJECT / RETURN / TRANSFER
    operator_id     bigint      not null,
    operator_name   varchar(64) not null,
    action_time     timestamptz not null,
    remark          varchar(512),
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp
);
-- 为表添加注释
COMMENT ON TABLE biz_process_action IS '流程操作记录表：记录用户在流程实例中对某任务执行的具体操作（如审批、驳回等）';

-- 为各字段添加注释
COMMENT ON COLUMN biz_process_action.id IS '主键，自增ID';
COMMENT ON COLUMN biz_process_action.process_inst_id IS '流程实例ID，标识该操作所属的流程执行实例';
COMMENT ON COLUMN biz_process_action.node_inst_id IS '节点实例ID，标识该操作发生的流程节点实例';
COMMENT ON COLUMN biz_process_action.task_id IS '任务ID，关联 process_task 表的 id 字段，表示具体被操作的任务';
COMMENT ON COLUMN biz_process_action.action_type IS '操作类型：APPROVE（同意）、REJECT（拒绝）、RETURN（退回）、TRANSFER（转办）等';
COMMENT ON COLUMN biz_process_action.operator_id IS '操作人用户ID';
COMMENT ON COLUMN biz_process_action.operator_name IS '操作人姓名';
COMMENT ON COLUMN biz_process_action.action_time IS '实际执行操作的时间（带时区）';
COMMENT ON COLUMN biz_process_action.remark IS '操作备注，最大长度512字符，可用于填写驳回原因、转办说明等';
COMMENT ON COLUMN biz_process_action.created_at IS '记录创建时间，默认为当前时间戳（带时区）';
COMMENT ON COLUMN biz_process_action.updated_at IS '记录最后更新时间，默认为当前时间戳（带时区）';