-- 标准项的值

create table biz_std_content_value
(
    id         bigint primary key generated by default as identity,
    item_id    bigint      not null references biz_std_item (id),
    field_id   bigint      not null references biz_std_content_field (id),
    value_str  VARCHAR(1024),
    value_num  DECIMAL(18, 2),
    value_date DATE,
    value_json JSONB,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);