create TABLE biz_process_route_def
(
    id             bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    process_def_id bigint NOT NULL,
    from_node_id   bigint NOT NULL,
    to_node_id     bigint NOT NULL,
    condition_expr varchar(512), -- 如 amount > 10000
    priority       int    NOT NULL
);
COMMENT ON TABLE biz_process_route_def IS
    '业务流程路由定义表：存储流程节点间的流转规则（含条件分支与默认路由），支撑流程引擎动态决策。';

COMMENT ON COLUMN biz_process_route_def.id IS
    '路由定义唯一标识（主键）';

COMMENT ON COLUMN biz_process_route_def.process_def_id IS
    '所属流程定义ID，逻辑外键关联 biz_process_def.id。用于隔离不同流程的路由规则。';

COMMENT ON COLUMN biz_process_route_def.from_node_id IS
    '起始节点ID，逻辑外键关联 biz_process_node_def.id。标识路由起点（如 APPROVAL 节点）。';

COMMENT ON COLUMN biz_process_route_def.to_node_id IS
    '目标节点ID，逻辑外键关联 biz_process_node_def.id。标识路由终点（如 PARALLEL 分支或 END 节点）。';

COMMENT ON COLUMN biz_process_route_def.condition_expr IS
    '路由条件表达式（SpEL/OGNL），示例：amount > 10000 || dept == ''FINANCE''。
    - NULL 或空字符串：表示默认路由（无条件必走路径）
    - 多条件路由：按 priority 排序匹配
    - 安全提示：需在应用层校验表达式安全性，避免注入风险';

COMMENT ON COLUMN biz_process_route_def.priority IS
    '路由优先级（数值越小优先级越高）。当同一 from_node_id 存在多条满足条件的路由时：
    - 优先选择 priority 最小的路由
    - 建议范围：0～999（0=最高优先级默认路由）
    - 同优先级多路由视为配置错误，需业务校验';