CREATE TABLE biz_process_task
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    process_inst_id bigint,
    node_inst_id    bigint,
    assignee_id     varchar(64),
    assignee_name   varchar(64),
    task_status     varchar(32), -- TODO / DONE / TRANSFERRED
    receive_time    timestamptz NOT NULL,
    complete_time   timestamp            DEFAULT NULL,
    created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 为表添加注释
COMMENT ON TABLE biz_process_task IS '审批任务表（按处理人维度）';

-- 为各字段添加注释
COMMENT ON COLUMN biz_process_task.id IS '主键，任务ID';
COMMENT ON COLUMN biz_process_task.process_inst_id IS '流程实例ID，关联流程定义的某一次执行实例';
COMMENT ON COLUMN biz_process_task.node_inst_id IS '节点实例ID，表示该任务所属的流程节点实例';
COMMENT ON COLUMN biz_process_task.assignee_id IS '任务处理人ID，通常是用户唯一标识（如用户ID或工号）';
COMMENT ON COLUMN biz_process_task.assignee_name IS '任务处理人姓名';
COMMENT ON COLUMN biz_process_task.task_status IS '任务状态：TODO（待处理）、DONE（已完成）、TRANSFERRED（已转办）';
COMMENT ON COLUMN biz_process_task.receive_time IS '任务接收时间';
COMMENT ON COLUMN biz_process_task.complete_time IS '任务完成时间';