create table biz_std
(
    id         bigint primary key generated by default as identity,
    std_no     varchar(128) unique,
    std_name   varchar(256) not null unique,
    version    int          not null,
    -- 标准内容
    content_id bigint,
    -- 标准发文
    issue_id   bigint,
    org_id     bigint,
    org_name   varchar(64),
    created_by bigint,
    username   varchar(64),
    status     varchar(32),
    created_at timestamptz  not null default current_timestamp,
    updated_at timestamptz  not null default current_timestamp
);

COMMENT ON COLUMN biz_std.status IS 'DRAFT        草稿
SUBMITTED    已提交（进入流程）
APPROVING    审批中
APPROVED     已批准
REJECTED     已驳回
CANCELLED    已撤回（可选）';