CREATE TABLE biz_process_instance
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    process_def_id  bigint,
    process_code    varchar(64),
    process_version int,
    business_key    varchar(64), -- 业务主键
    business_type   varchar(32),
    status          varchar(32), -- RUNNING / COMPLETED / REJECTED
    start_user_id   varchar(64),
    start_time      timestamp,
    end_time        timestamp
)
