-- 标准项的表头
create table biz_std_content_field
(
    id            bigint primary key generated by default as identity,
    --
    cat_id        bigint      not null references dict_std_content_cat (id),
    prop_id       bigint      NOT NULL references dict_std_content_prop (id),
    field_name    varchar(64) not null,
    field_type    VARCHAR(32) NOT NULL default 'TEXT', --
    description   text,
    required      BOOLEAN              DEFAULT FALSE,
    default_value VARCHAR(255)         default NULL,
    order_no      INT,
    config        jsonb,
    is_enabled    boolean              default true,
--     is_deleted    boolean              default false,
    created_at    timestamptz NOT NULL default CURRENT_TIMESTAMP,
    updated_at    timestamptz not null default current_timestamp,
    unique (cat_id, prop_id, field_name)
);

COMMENT ON COLUMN biz_std_content_field.field_type is 'text | textarea | number | date | datetime
select | multiselect | checkbox | radio
user | dept | attachment';