create table dict_std_content_prop
(
    id         bigint primary key generated by default as identity,
    code       varchar(32),
    prop_name  varchar(32) not null,
    sort_order int         not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

COMMENT ON TABLE dict_std_content_prop IS '标准项属性字典';

-- 字段注释
COMMENT ON COLUMN dict_std_content_prop.id IS '主键，自增ID';
COMMENT ON COLUMN dict_std_content_prop.code IS '数据属性编码，唯一标识';
COMMENT ON COLUMN dict_std_content_prop.prop_name IS '数据属性名称';
COMMENT ON COLUMN dict_std_content_prop.sort_order IS '排序';
COMMENT ON COLUMN dict_std_content_prop.created_at IS '创建时间';
COMMENT ON COLUMN dict_std_content_prop.updated_at IS '最后更新时间';

INSERT INTO dict_std_content_prop(code, prop_name, sort_order)
VALUES ('TECH', '技术属性', 1),
       ('BUSINESS', '业务属性', 2),
       ('MANAGEMENT', '管理属性', 3);