-- 字典标准类型表（存储多选的标准类型）
CREATE TABLE dict_std_type
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code       VARCHAR(32),
    type_name  VARCHAR(64) NOT NULL UNIQUE,

    is_deleted BOOLEAN     NOT NULL DEFAULT false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

-- 为字段添加注释
COMMENT ON TABLE dict_std_type IS '标准类型表';
COMMENT ON COLUMN dict_std_type.code IS '编码';
COMMENT ON COLUMN dict_std_type.type_name IS '标准类型名称';
COMMENT ON COLUMN dict_std_type.is_deleted IS '是否删除标记';
COMMENT ON COLUMN dict_std_type.created_at IS '创建时间';
COMMENT ON COLUMN dict_std_type.updated_at IS '更新时间';

-- 初始化字典数据
INSERT INTO dict_std_type (code, type_name)
VALUES ('SYS_EQUIP_STD', '系统/设备标准（包括技术要求和试验检验）'),
       ('OVERALL_TECH_COND', '总体技术条件'),
       ('TEST_METHOD', '试验方法/调试方法/标定方法/安装技术要求'),
       ('METROLOGY_SPEC', '计量规范'),
       ('TECH_SPEC_NON_TEST', '技术条件/技术规范（不含试验检验）');

