-- 标准项数据类型
create table dict_std_content_cat
(
    id         bigint primary key generated by default as identity,
    code       varchar(32),
    cat_name   varchar(32) not null,
    sort_order int         not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

-- 表注释
COMMENT ON TABLE dict_std_content_cat IS '标准项数据类型';

-- 字段注释
COMMENT ON COLUMN dict_std_content_cat.id IS '主键，自增ID';
COMMENT ON COLUMN dict_std_content_cat.code IS '数据类型编码，唯一标识';
COMMENT ON COLUMN dict_std_content_cat.cat_name IS '数据类型名称';
COMMENT ON COLUMN dict_std_content_cat.sort_order IS '排序';
COMMENT ON COLUMN dict_std_content_cat.created_at IS '创建时间';
COMMENT ON COLUMN dict_std_content_cat.updated_at IS '最后更新时间';

INSERT INTO dict_std_content_cat(code, cat_name, sort_order)
VALUES ('ORIGIN', '原始数据', 1),
       ('METRICS', '指标数据', 2);