-- 标准类别
create table dict_std_category
(
    id         bigint primary key generated by default as identity,
    -- 类别名
    cat_name   varchar(64) not null,
    code       varchar(32),
    is_deleted boolean     not null default false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);