-- 标准和类别多对多关联
create table rel_std_category
(
    id         bigint primary key generated by default as identity,
    -- 标准ID
    std_id     bigint      not null,
    -- 类别ID
    cat_id     bigint      not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
)