CREATE TABLE sys_attachment
(
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    biz_type            VARCHAR(50)  NOT NULL,
    biz_id              BIGINT       NOT NULL,
    version             INT          NOT NULL DEFAULT 1,
    is_latest           BOOLEAN      NOT NULL DEFAULT TRUE,

    file_name           VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(64),
    file_size           BIGINT       NOT NULL,
    file_url            VARCHAR(255) NOT NULL,

    attach_category     VARCHAR(50),
    attach_desc         VARCHAR(500),

    process_instance_id BIGINT,
    task_node_code      VARCHAR(50),

--     created_by          BIGINT       NOT NULL REFERENCES sys_user (id),
    created_by          BIGINT       NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN      NOT NULL DEFAULT false
);
COMMENT ON TABLE sys_attachment IS '系统通用附件表';

COMMENT ON COLUMN sys_attachment.biz_type IS '业务类型，如 STD_PLAN / CONTRACT / REIMBURSE';
COMMENT ON COLUMN sys_attachment.biz_id IS '业务数据ID';

COMMENT ON COLUMN sys_attachment.attach_category IS '附件分类(立项材料/审批材料等)';
